title: Maryam Rezaee
short_description: A computer science researcher specialising in LLM Interpretability and Cognitively-Inspired AI.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maryamrezaee.me" # the base hostname & protocol

user_name: Maryam Rezaee
# user_title: AI Researcher
user_location: Tehran, Iran

home_description: |
  It is I, Maryam!
  Welcome to my digital ecosystem. This space serves as the central hub for my multidisciplinary world. Here, you shall find my background and experience, academic research in trustworthy AI, and various software development and graphic design projects, all alongside my technical writing and personal journals, poetry, and art.
  So step in. Click around. See what you find. You can always ping me if you get lost :)

email: ms.maryamrezaee@gmail.com
telegram_username: msmrexe
github_username: msmrexe
tumblr_username: msmrexe

design_url: "https://design.maryamrezaee.me"
lab_url: "https://lab.maryamrezaee.me"
me_url: "https://me.maryamrezaee.me"

google-analytics:
  id: "G-0R7D6BFS2Z"

exclude: ['package.json', 'package-lock.json', 'src' , 'node_modules', 'gulpfile.js']
