# Site settings
title: Maryam Rezaee | AI Researcher
description: A computer science researcher specializing in LLM Interpretability and Cognitively-Inspired AI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://msmaryamrezaee.github.io" # the base hostname & protocol

# User settings
username: Maryam Rezaee

user_description: |
  It is I, Maryam!

  I am a researcher navigating the chaotic intersection of LLM Interpretability and Cognitively-Inspired AI. I don’t just want models to generate text; I want to understand and control how they do it. In other words, my goal is to tame the “black box” by integrating human-like structure and symbolic reasoning into NNs, making them into more than just statistically fluent machines.

  My journey has taken me from theoretical narrative algorithms to rigorous concept-based interpretability. Currently, I am expanding my focus towards Neurosymbolic architectures, aiming to build systems that don’t just predict the next token, but reason in a way that is verifiable, explainable, and aligned with human thought.

user_title: AI Researcher
email: msmaryamrezaee@gmail.com
telegram_username: msmrexe
github_username: msmrexe

# Google-analytics
google-analytics:
  id: "G-0R7D6BFS2Z"

exclude: ['package.json', 'package-lock.json', 'src' , 'node_modules', 'gulpfile.js']
