# Site settings
title: Maryam Rezaee | AI Researcher
description: A computer science researcher specializing in LLM Interpretability and Cognitively-Inspired AI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://msmaryamrezaee.github.io" # the base hostname & protocol

# User settings
username: Maryam Rezaee
user_description: |
  A computer science researcher specializing in LLM Interpretability and Cognitively-Inspired AI. My objective is to develop robust, explainable systems by investigating the integration of human inductive biases and symbolic reasoning structures into neural models. My foundational experience includes a thesis on LLM input-output interactions and research in concept-based interpretability. I am now expanding this focus toward neurosymbolic architectures, evidenced by projects in program generation. I seek to advance this research with the aim of developing models capable of more robust and human-aligned reasoning.
user_title: AI Researcher
email: msmaryamrezaee@gmail.com
telegram_username: msmrexe
github_username: msmrexe

# Google-analytics
google-analytics:
  id: "G-0R7D6BFS2Z"

exclude: ['package.json', 'package-lock.json', 'src' , 'node_modules', 'gulpfile.js']
